# Generated by Django 3.1.4 on 2021-01-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_collection_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection',
            field=models.ImageField(blank=True, null=True, upload_to='collection'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.ImageField(blank=True, null=True, upload_to='collection'),
        ),
    ]
