# Generated by Django 3.1.4 on 2021-01-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210101_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='note',
        ),
    ]
