# Generated by Django 3.1.4 on 2021-01-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210101_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='note',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='collection',
        ),
        migrations.AddField(
            model_name='collection',
            name='note_image',
            field=models.ImageField(null=True, upload_to='collection'),
        ),
    ]
