# Generated by Django 3.1.4 on 2021-01-02 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210101_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='collection_of_notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections_of_notes', to='core.collection'),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
