# Generated by Django 3.1.4 on 2021-01-03 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210102_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='collection_of_notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.collection'),
        ),
    ]
